-- Script was generated by Devart Entity Developer, Version 6.10.1189.0
-- Script date 2021. 03. 21. 13:17:30
-- Target Server: SQL Server
-- Server Version: 2016

-- 
-- Creating a table dbo.Numbers 
-- 
CREATE TABLE dbo.Numbers (
   Id SMALLINT NOT NULL IDENTITY,
   NumberString NVARCHAR(4000) NOT NULL,
   CONSTRAINT PK_Numbers PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table dbo.People 
-- 
CREATE TABLE dbo.People (
   Id SMALLINT NOT NULL IDENTITY,
   Name NVARCHAR(4000) NOT NULL,
   Remark NVARCHAR(4000) NOT NULL,
   CONSTRAINT PK_People PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table dbo.Numbers_People 
-- 
CREATE TABLE dbo.Numbers_People (
   Id SMALLINT NOT NULL,
   Id1 SMALLINT NOT NULL,
   CONSTRAINT PK_Numbers_People PRIMARY KEY (Id, Id1),
   CONSTRAINT FK_Numbers_People_Numbers_0 FOREIGN KEY (Id) REFERENCES dbo.Numbers (Id),
   CONSTRAINT FK_Numbers_People_People_1 FOREIGN KEY (Id1) REFERENCES dbo.People (Id)
)
GO

